default_language_version:
    python: python3.9

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        args: [-i , -vv]
        types: [python]

  - repo: local
    hooks:
      - id: tox
        name: run test environment
        language: system
        entry: tox
        pass_filenames: false
        always_run: true
